name:

SUBZERO-MD-X-MR-FRANK

on:

workflow_dispatch:

jobs:

loop-task:

runs-on: ubuntu-latest

steps:

-name: Checkout Code

uses: actions/checkout@v3

-name: Setup Node.js

uses: actions/setup-node@v3

with:

node-version: 20name: Install Dependencies

run: npm install

name: Run Bot (loop & auto-restarti

run: |

echo "Running SUBZERO-MD in auto-Ð³

timeout 18000 bash -c 'while true
